# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180115_0743'),
    ]

    operations = [
        migrations.RunSQL(
            sql=['ALTER TABLE blog_article MODIFY content LONGTEXT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
            reverse_sql=['ALTER TABLE blog_article MODIFY content LONGTEXT']  
        )
    ]
